package co.spribe.models;

import co.spribe.utils.JsonUtil;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.Objects;

@JsonIgnoreProperties(ignoreUnknown = true)
public class PlayerPojo {
  @JsonProperty("age")
  private Integer age;

  @JsonProperty("gender")
  private String gender;

  @JsonProperty("id")
  private Long id;

  @JsonProperty("login")
  private String login;

  @JsonProperty("password")
  private String password;

  @JsonProperty("role")
  private String role;

  @JsonProperty("screenName")
  private String screenName;

  public Integer getAge() {
    return age;
  }

  public PlayerPojo setAge(Integer age) {
    this.age = age;
    return this;
  }

  public String getGender() {
    return gender;
  }

  public PlayerPojo setGender(String gender) {
    this.gender = gender;
    return this;
  }

  public Long getId() {
    return id;
  }

  public PlayerPojo setId(Long id) {
    this.id = id;
    return this;
  }

  public String getLogin() {
    return login;
  }

  public PlayerPojo setLogin(String login) {
    this.login = login;
    return this;
  }

  public String getPassword() {
    return password;
  }

  public PlayerPojo setPassword(String password) {
    this.password = password;
    return this;
  }

  public String getRole() {
    return role;
  }

  public PlayerPojo setRole(String role) {
    this.role = role;
    return this;
  }

  public String getScreenName() {
    return screenName;
  }

  public PlayerPojo setScreenName(String screenName) {
    this.screenName = screenName;
    return this;
  }

  // 'id' is excluded from equals/hashCode since it is generated by API
  @Override
  public boolean equals(Object o) {
    if (this == o) return true;
    if (!(o instanceof PlayerPojo)) return false;
    PlayerPojo that = (PlayerPojo) o;
    return Objects.equals(age, that.age)
        && Objects.equals(gender, that.gender)
        && Objects.equals(login, that.login)
        && Objects.equals(password, that.password)
        && Objects.equals(role, that.role)
        && Objects.equals(screenName, that.screenName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(age, gender, login, password, role, screenName);
  }

  @Override
  public String toString() {
    return String.format(
        "PlayerPojo{age=%d, gender='%s', login='%s', password='%s', role='%s', screenName='%s'}",
        age, gender, login, password, role, screenName);
  }

  @Override
  public PlayerPojo clone() {
    return JsonUtil.cloneObject(this, PlayerPojo.class);
  }
}
